file_mappings = {
	'dio' : {
		"arch/renesas/rh850_x/drivers/Dio.c" : "arch/renesas/rh850_x/drivers/Dio.c",
		"arxml/rh850/ArcCore_EcucDefs_rh850_Dio.arxml" : "arxml/rh850/ArcCore_EcucDefs_rh850_Dio.arxml",
		"generators/mcal/rh850/Dio.echk" : "generators/mcal/rh850/Dio.echk",
		"generators/mcal/rh850/Dio.expt" : "generators/mcal/rh850/Dio.expt",
		"include/Dio.h" : "include/Dio.h",
		"stylesheets/dio.yaml" : "stylesheets/dio.yaml",
	},
	'port' : {
		"arxml/rh850/ArcCore_EcucDefs_rh850_Port.arxml" : "arxml/rh850/ArcCore_EcucDefs_rh850_Port.arxml",
		"arxml/rh850/PortPins_rh850.yaml" : "arxml/rh850/PortPins_rh850.yaml",
		"arch/renesas/rh850_x/drivers/rh850_portdefs.h" : "arch/renesas/rh850_x/drivers/rh850_portdefs.h",
		"arch/renesas/rh850_x/drivers/Port_RegFinder.c" : "arch/renesas/rh850_x/drivers/Port_RegFinder.c",
		"arch/renesas/rh850_x/drivers/Port_RegFinder.h" : "arch/renesas/rh850_x/drivers/Port_RegFinder.h",
		"arch/renesas/rh850_x/drivers/Port.c" : "arch/renesas/rh850_x/drivers/Port.c",
		"generators/mcal/rh850/Port.echk" : "generators/mcal/rh850/Port.echk",
		"generators/mcal/rh850/Port.expt" : "generators/mcal/rh850/Port.expt",
		"stylesheets/port.yaml" : "stylesheets/port.yaml",
		"include/Port.h" : "include/Port.h",
	},
	'can' : {
		"arch/renesas/rh850_x/drivers/Can.c" : "arch/renesas/rh850_x/drivers/Can.c",
		"arch/renesas/rh850_x/drivers/CanRegs.h" : "arch/renesas/rh850_x/drivers/CanRegs.h",
		"arxml/rh850/ArcCore_EcucDefs_rh850_Can.arxml" : "arxml/rh850/ArcCore_EcucDefs_rh850_Can.arxml",
		"generators/mcal/rh850/Can.echk" : "generators/mcal/rh850/Can.echk",
		"generators/mcal/rh850/Can.expt" : "generators/mcal/rh850/Can.expt",
		"generators/utils/CanHelpersRh850.eext" : "generators/utils/CanHelpersRh850.eext",
		"include/Can.h" : "include/Can.h",
		"stylesheets/can.yaml" : "stylesheets/can.yaml",
	},
	'fr' : {
		"arxml/rh850/ArcCore_EcucDefs_rh850_Fr.arxml" : "arxml/rh850/ArcCore_EcucDefs_rh850_Fr.arxml",
		"arch/renesas/rh850_x/drivers/Fr_Internal.h" : "arch/renesas/rh850_x/drivers/Fr_Internal.h",
		"arch/renesas/rh850_x/drivers/Fr_Internal.c" : "arch/renesas/rh850_x/drivers/Fr_Internal.c",
		"arch/renesas/rh850_x/drivers/Fr.c" : "arch/renesas/rh850_x/drivers/Fr.c",
		"generators/mcal/rh850/Fr.echk" : "generators/mcal/rh850/Fr.echk",
		"generators/mcal/rh850/Fr.expt" : "generators/mcal/rh850/Fr.expt",
		"generators/utils/FrHelpers.eext" : "generators/utils/FrHelpers.eext",
		"include/Fr.h" : "include/Fr.h",
		"include/Fr_GeneralTypes.h" : "include/Fr_GeneralTypes.h",
	},
	'gpt' : {
		"arxml/rh850/ArcCore_EcucDefs_rh850_Gpt.arxml" : "arxml/rh850/ArcCore_EcucDefs_rh850_Gpt.arxml",
		"arch/renesas/rh850_x/drivers/Gpt_tauj.c" : "arch/renesas/rh850_x/drivers/Gpt_tauj.c",
		"drivers/Gpt/Gpt.c" : "drivers/Gpt/Gpt.c",
		"drivers/Gpt/Gpt_Internal.h" : "drivers/Gpt/Gpt_Internal.h",
		"generators/mcal/rh850/Gpt.echk" : "generators/mcal/rh850/Gpt.echk",
		"generators/mcal/rh850/Gpt.expt" : "generators/mcal/rh850/Gpt.expt",
		"include/Gpt.h" : "include/Gpt.h",
		"include/Gpt_ConfigTypes.h" : "include/Gpt_ConfigTypes.h",
		"stylesheets/Gpt.yaml" : "stylesheets/Gpt.yaml",
	},
	'mcu' : {
		"arch/renesas/rh850_x/drivers/Mcu.c" : "arch/renesas/rh850_x/drivers/Mcu.c",
		"include/renesas/Mcu.h" : "include/renesas/Mcu.h",
	},
	'kernel' : {
		"arch/renesas/rh850_x/kernel/dr7f701503.dvf.h" : "arch/renesas/rh850_x/kernel/dr7f701503.dvf.h",
		"arch/renesas/rh850_x/kernel/crt0.sx" : "arch/renesas/rh850_x/kernel/crt0.sx",
		"arch/renesas/rh850_x/kernel/arch_stack.h" : "arch/renesas/rh850_x/kernel/arch_stack.h",
		"arch/renesas/rh850_x/kernel/arch_krn.sx" : "arch/renesas/rh850_x/kernel/arch_krn.sx",
		"arch/renesas/rh850_x/kernel/arch.c" : "arch/renesas/rh850_x/kernel/arch.c",
		"arch/renesas/rh850_x/kernel/sys_tick.c" : "arch/renesas/rh850_x/kernel/sys_tick.c",
		"arch/renesas/rh850_x/kernel/stack.h" : "arch/renesas/rh850_x/kernel/stack.h",
		"arch/renesas/rh850_x/kernel/irq_types.h" : "arch/renesas/rh850_x/kernel/irq_types.h",
		"arch/renesas/rh850_x/kernel/irq_rh850f1h.h" : "arch/renesas/rh850_x/kernel/irq_rh850f1h.h",
		"arch/renesas/rh850_x/kernel/irq.c" : "arch/renesas/rh850_x/kernel/irq.c",
	},
	'common' : {
		"arxml/rh850/McalImplementations_rh850f1h.arxml" : "arxml/rh850/McalImplementations_rh850f1h.arxml",
		"arxml/McalDefinitions.yaml" : "arxml/McalDefinitions.yaml",
		"arxml/autosar/ECUConfigurationParameters_412.arxml" : "arxml/autosar/ECUConfigurationParameters_412.arxml",
		"generators/utils/Helpers.eext" : "generators/utils/Helpers.eext",
		"include/Arc_Types.h" : "include/Arc_Types.h",
	},
	'Misc' : {
		"common/init.c" : "common/init.c",
		"common/printf.c" : "common/printf.c",
		"clib/assert.h" : "clib/assert.h",
		"integration/MemMap.h" : "integration/MemMap.h",
        "integration/Arc_MemMap.h" : "integration/Arc_MemMap.h",
	},
	'buildsystem' : {
		"makefile" : "makefile",
		"boards/board_common.mk" : "boards/board_common.mk",
		"arch/renesas/rh850_x/scripts/ghs.mk" : "arch/renesas/rh850_x/scripts/ghs.mk",
		"arch/renesas/rh850_x/scripts/linkscript_ghs.ldf" : "arch/renesas/rh850_x/scripts/linkscript_ghs.ldf",
		"scripts/linker/memory_mcu.ldf" : "scripts/linker/memory_mcu.ldf",
        "scripts/linker/compiler.ldf" : "scripts/linker/compiler.ldf",
        "scripts/memory_footprint_ghs.awk" : "scripts/memory_footprint_ghs.awk",
		"scripts/project_defaults.mk" : "scripts/project_defaults.mk",
		"scripts/rules.mk" : "scripts/rules.mk",
		"scripts/version_check.mk" : "scripts/version_check.mk",
		"scripts/cc_ghs.mk" : "scripts/cc_ghs.mk",
		"boards/rh850_f1h/board_info.txt":"boards/rh850_f1h/board_info.txt",
		"boards/rh850_f1h/build_config.mk":"boards/rh850_f1h/build_config.mk",
		"boards/rh850_f1h/rh850_f1h.yaml" : "boards/rh850_f1h/rh850_f1h.yaml",
	},
	'project_files' : {
		".project" : ".project",
		".cproject" : ".cproject",
		".settings/com.arccore.prefs" : ".settings/com.arccore.prefs",
		".settings/org.eclipse.core.resources.prefs" : ".settings/org.eclipse.core.resources.prefs",
	},
}

patch_file_mappings = {
    'patch' : {
        "build_config.mk" : "boards/rh850_f1h/build_config.mk",
    },
}