file_mappings = {
    'dio' : {
        "arxml/zynq/ArcCore_EcucDefs_Zynq_Dio.arxml" : "arxml/zynq/ArcCore_EcucDefs_Zynq_Dio.arxml",
        "generators/mcal/zynq/Dio.expt" : "generators/mcal/zynq/Dio.expt",
        "generators/mcal/zynq/Dio.echk" : "generators/mcal/zynq/Dio.echk",
        "generators/utils/DioHelpersZynq.eext":"generators/utils/DioHelpersZynq.eext",
        "stylesheets/dio.yaml" : "stylesheets/dio.yaml",
        "arch/arm/armv7_ar/drivers/Dio.c" : "arch/arm/armv7_ar/drivers/Dio.c",
        "include/Dio.h" : "include/Dio.h"
    },
    'mcu' : {
        "arxml/zynq/ArcCore_EcucDefs_Zynq_Mcu.arxml" : "arxml/zynq/ArcCore_EcucDefs_Zynq_Mcu.arxml",
        "generators/mcal/zynq/Mcu.echk" : "generators/mcal/zynq/Mcu.echk",
        "generators/mcal/zynq/Mcu.expt" : "generators/mcal/zynq/Mcu.expt",
        "generators/utils/McuHelpers.eext" : "generators/utils/McuHelpers.eext",
        "stylesheets/mcu.yaml" : "stylesheets/mcu.yaml",
        "arch/arm/armv7_ar/drivers/Mcu.c" : "arch/arm/armv7_ar/drivers/Mcu.c",
        "arch/arm/armv7_ar/drivers/zynq.h" : "arch/arm/armv7_ar/drivers/zynq.h",
        "include/arm/Mcu.h" : "include/arm/Mcu.h",
        "include/io.h" : "include/io.h",
        "include/arm/Cpu.h" : "include/arm/Cpu.h",
        "system/SchM/SchM_Mcu.h" : "system/SchM/SchM_Mcu.h",
		"include/irq.h" : "include/irq.h",
		"include/bit.h" : "include/bit.h",
    },
    'port' : {
        "arxml/zynq/ArcCore_EcucDefs_Zynq_Port.arxml" : "arxml/zynq/ArcCore_EcucDefs_Zynq_Port.arxml",
        "arxml/zynq/PortPins_zynq.yaml" : "arxml/zynq/PortPins_zynq.yaml",
        "generators/mcal/zynq/Port.expt" : "generators/mcal/zynq/Port.expt",
        "generators/mcal/zynq/Port.echk" : "generators/mcal/zynq/Port.echk",
        "generators/utils/PortHelpersZynq.eext":"generators/utils/PortHelpersZynq.eext",
        "stylesheets/port.yaml" : "stylesheets/port.yaml",
        "arch/arm/armv7_ar/drivers/Port.c" : "arch/arm/armv7_ar/drivers/Port.c",
        "include/Port.h" : "include/Port.h",
        "include/PortDefs.h" : "include/PortDefs.h",
        "arch/arm/armv7_ar/drivers/zynq_portdefs.h" : "arch/arm/armv7_ar/drivers/zynq_portdefs.h",
        "system/SchM/SchM_Port.h":"system/SchM/SchM_Port.h",
    },
    'kernel' : {
        "arch/arm/armv7_ar/kernel/arch_krn.sx" : "arch/arm/armv7_ar/kernel/arch_krn.sx",
        "arch/arm/armv7_ar/kernel/arch_offset.c" : "arch/arm/armv7_ar/kernel/arch_offset.c",
        "arch/arm/armv7_ar/kernel/arch_stack.h" : "arch/arm/armv7_ar/kernel/arch_stack.h",
        "arch/arm/armv7_ar/kernel/arch.c" : "arch/arm/armv7_ar/kernel/arch.c",
        "arch/arm/armv7_ar/kernel/core_cr4.h" : "arch/arm/armv7_ar/kernel/core_cr4.h",
        "arch/arm/armv7_ar/kernel/irq_zynq.h" : "arch/arm/armv7_ar/kernel/irq_zynq.h",
        "arch/arm/armv7_ar/kernel/irq.c" : "arch/arm/armv7_ar/kernel/irq.c",
        "arch/arm/armv7_ar/kernel/stack.h" : "arch/arm/armv7_ar/kernel/stack.h",
        "arch/arm/armv7_ar/kernel/startup_armv7-ar.sx" : "arch/arm/armv7_ar/kernel/startup_armv7-ar.sx",
        "arch/arm/armv7_ar/kernel/sys_tick.c" : "arch/arm/armv7_ar/kernel/sys_tick.c",
    },
    'icu' : {
        "arxml/zynq/ArcCore_EcucDefs_Zynq_Icu.arxml" : "arxml/zynq/ArcCore_EcucDefs_Zynq_Icu.arxml",
        "generators/mcal/zynq/Icu.expt" : "generators/mcal/zynq/Icu.expt",
        "generators/mcal/zynq/Icu.echk" : "generators/mcal/zynq/Icu.echk",
        "generators/utils/IcuHelpersZynq.eext":"generators/utils/IcuHelpersZynq.eext",
        "stylesheets/icu.yaml" : "stylesheets/icu.yaml",
        "arch/arm/armv7_ar/drivers/Icu.c" : "arch/arm/armv7_ar/drivers/Icu.c",
        "include/Icu.h" : "include/Icu.h",
        "include/Icu_Internal.h" : "include/Icu_Internal.h",
   },
   'pwm' : {
        "arxml/zynq/ArcCore_EcucDefs_Zynq_Pwm.arxml" : "arxml/zynq/ArcCore_EcucDefs_Zynq_Pwm.arxml",
        "generators/mcal/zynq/Pwm.expt" : "generators/mcal/zynq/Pwm.expt",
        "generators/mcal/zynq/Pwm.echk" : "generators/mcal/zynq/Pwm.echk",
        "generators/utils/PwmHelpers.eext":"generators/utils/PwmHelpers.eext",
        "stylesheets/pwm.yaml" : "stylesheets/pwm.yaml",
        "arch/arm/armv7_ar/drivers/Pwm.c" : "arch/arm/armv7_ar/drivers/Pwm.c",
        "include/Pwm.h" : "include/Pwm.h",
        "system/SchM/SchM_Pwm.h":"system/SchM/SchM_Pwm.h",
    },
    'adc' : {
        "arxml/zynq/ArcCore_EcucDefs_Zynq_Adc.arxml" : "arxml/zynq/ArcCore_EcucDefs_Zynq_Adc.arxml",
        "generators/mcal/zynq/Adc.expt" : "generators/mcal/zynq/Adc.expt",
        "generators/mcal/zynq/Adc.echk" : "generators/mcal/zynq/Adc.echk",
        "generators/utils/AdcHelpersZynq.eext":"generators/utils/AdcHelpersZynq.eext",
        "stylesheets/Adc.yaml" : "stylesheets/Adc.yaml",
        "arch/arm/armv7_ar/drivers/Adc.c" : "arch/arm/armv7_ar/drivers/Adc.c",
        "include/Adc.h" : "include/Adc.h",
        "include/arm/armv7_ar/Adc_ConfigTypes.h" : "include/arm/armv7_ar/Adc_ConfigTypes.h",
        "drivers/Adc_Internal.c" : "drivers/Adc_Internal.c",
        "drivers/Adc_Internal.h" : "drivers/Adc_Internal.h",
    },
    'spi' : {
        "arxml/zynq/ArcCore_EcucDefs_Zynq_Spi.arxml" : "arxml/zynq/ArcCore_EcucDefs_Zynq_Spi.arxml",
        "generators/mcal/zynq/Spi.expt" : "generators/mcal/zynq/Spi.expt",
        "generators/mcal/zynq/Spi.echk" : "generators/mcal/zynq/Spi.echk",
        "stylesheets/spi.yaml" : "stylesheets/spi.yaml",
        "arch/arm/armv7_ar/drivers/Spi.c" : "arch/arm/armv7_ar/drivers/Spi.c",
        "arch/arm/armv7_ar/drivers/Spi_zynq.c" : "arch/arm/armv7_ar/drivers/Spi_zynq.c",
        "include/Spi.h" : "include/Spi.h",
        "include/Spi_Internal.h" : "include/Spi_Internal.h",
    },
    'wdg' : {
        "arxml/zynq/ArcCore_EcucDefs_Zynq_Wdg.arxml" : "arxml/zynq/ArcCore_EcucDefs_Zynq_Wdg.arxml",
        "generators/mcal/zynq/Wdg.expt" : "generators/mcal/zynq/Wdg.expt",
        "generators/mcal/zynq/Wdg.echk" : "generators/mcal/zynq/Wdg.echk",
        "stylesheets/wdg.yaml" : "stylesheets/wdg.yaml",
        "arch/arm/armv7_ar/drivers/Wdg.c" : "arch/arm/armv7_ar/drivers/Wdg.c",
        "include/Wdg.h" : "include/Wdg.h",
    },
    'gpt' : {
        "arxml/zynq/ArcCore_EcucDefs_Zynq_Gpt.arxml" : "arxml/zynq/ArcCore_EcucDefs_Zynq_Gpt.arxml",
        "generators/mcal/zynq/Gpt.expt" : "generators/mcal/zynq/Gpt.expt",
        "generators/mcal/zynq/Gpt.echk" : "generators/mcal/zynq/Gpt.echk",
        "generators/utils/GptHelpersZynq.eext":"generators/utils/GptHelpersZynq.eext",
        "stylesheets/Gpt.yaml" : "stylesheets/Gpt.yaml",
        "arch/arm/armv7_ar/drivers/Gpt.c" : "arch/arm/armv7_ar/drivers/Gpt.c",
        "include/Gpt.h" : "include/Gpt.h",
        "include/Gpt_ConfigTypes.h" : "include/Gpt_ConfigTypes.h",
        "include/isr.h" : "include/isr.h",
    },
   'common' : {
        "arxml/McalDefinitions.yaml" : "arxml/McalDefinitions.yaml",
        "arxml/autosar/ECUConfigurationParameters_412.arxml" : "arxml/autosar/ECUConfigurationParameters_412.arxml",
        "arxml/zynq/McalImplementations_zynq.arxml" : "arxml/zynq/McalImplementations_zynq.arxml",
        "generators/utils/Helpers.eext" : "generators/utils/Helpers.eext",
        "include/Arc_Types.h" : "include/Arc_Types.h",
    },
    'buildsystem' : {
        "makefile" : "makefile",
        "boards/board_common.mk" : "boards/board_common.mk",
        "arch/arm/armv7_ar/scripts/gcc.mk" : "arch/arm/armv7_ar/scripts/gcc.mk",
        "arch/arm/armv7_ar/scripts/linkscript_gcc.ldf" : "arch/arm/armv7_ar/scripts/linkscript_gcc.ldf",
        "scripts/project_defaults.mk" : "scripts/project_defaults.mk",
        "scripts/rules.mk" : "scripts/rules.mk",
        "scripts/version_check.mk" : "scripts/version_check.mk",
        "scripts/cc_gcc.mk" : "scripts/cc_gcc.mk",
        "boards/zynq_zc702/board_info.txt":"boards/zynq_zc702/board_info.txt",
        "boards/zynq_zc702/build_config.mk":"boards/zynq_zc702/build_config.mk",
        "boards/zynq_zc702/memory.ldf":"boards/zynq_zc702/memory.ldf",
        "boards/board_common.mk":"boards/board_common.mk",
    },
    'os' : {
        "system/Os/makefile" : "system/Os/makefile",
    },

    'Misc' : {
        "include/timer.h" : "include/timer.h",
        "include/sys/queue.h" : "include/sys/queue.h",
        "common/init.c" : "common/init.c",
        "common/printf.c" : "common/printf.c",
        "clib/assert.h" : "clib/assert.h",
        #=======================================================================
        # "system/Os/asm_offset.c":"system/Os/asm_offset.c",
        # "system/Os/include/os_i.h":"system/Os/include/os_i.h",
        # "system/Os/include/os_internal.h":"system/Os/include/os_internal.h",
        # "system/Os/include/os_sys.h":"system/Os/include/os_sys.h",
        # "integration/MemMap.h" : "integration/MemMap.h",
        # "integration/Arc_MemMap.h" : "integration/Arc_MemMap.h",
        #=======================================================================
    },
    'project_files' : {
        ".project" : ".project",
        ".cproject" : ".cproject",
        ".settings/com.arccore.prefs" : ".settings/com.arccore.prefs",
        ".settings/org.eclipse.core.resources.prefs" : ".settings/org.eclipse.core.resources.prefs",
    }

}
patch_file_mappings = {
    'patch' : {
        "build_config.mk" : "boards/zynq_zc702/build_config.mk",
    },
}