/**
 * RTE Types Workarounds Header File
 *
 * This file is used to fix some problems when using the RTE together
 * with files produced elsewhere. Each workaround has its own documentation.
 */

#ifndef RTE_TYPE_WORKAROUNDS_H_
#define RTE_TYPE_WORKAROUNDS_H_

/**
 * SWCs generated by Simulink have internal typedefs for types that are only used within the SWC. 
 * If another SWC (also generated by Simulink) uses the same type, but on a port, this type will be
 * part of the AUTOSAR model and hence be generated in Rte_Type.h. To protect against double declaration
 * each typedef in the Simulink files is guarded like this:
 *
 * #ifndef _DEFINED_TYPEDEF_FOR_T_U_mV_1_1_s16_
 * #define _DEFINED_TYPEDEF_FOR_T_U_mV_1_1_s16_
 * typedef int16_T T_U_mV_1_1_s16;
 * #endif
 *       
 * By defining these macros we can make it easier to integrate Simulink SWCs with the ArcCore RTE.
 * Note that this is not AUTOSAR standard.
 */
#define _DEFINED_TYPEDEF_FOR_AnalogValue_

#define _DEFINED_TYPEDEF_FOR_ComM_InhibitionStatusType_

#define _DEFINED_TYPEDEF_FOR_ComM_ModeType_

#define _DEFINED_TYPEDEF_FOR_ComM_UserHandleType_

#define _DEFINED_TYPEDEF_FOR_ConstVoidPtr_

#define _DEFINED_TYPEDEF_FOR_Dcm_ConfirmationStatusType_

#define _DEFINED_TYPEDEF_FOR_Dcm_NegativeResponseCodeType_

#define _DEFINED_TYPEDEF_FOR_Dcm_OpStatusType_

#define _DEFINED_TYPEDEF_FOR_Dcm_ProtocolType_

#define _DEFINED_TYPEDEF_FOR_Dcm_RoeStateType_

#define _DEFINED_TYPEDEF_FOR_Dcm_SecLevelType_

#define _DEFINED_TYPEDEF_FOR_Dcm_SesCtrlType_

#define _DEFINED_TYPEDEF_FOR_Dem_DTCFormatType_

#define _DEFINED_TYPEDEF_FOR_Dem_DTCOriginType_

#define _DEFINED_TYPEDEF_FOR_Dem_DTCStatusMaskType_

#define _DEFINED_TYPEDEF_FOR_Dem_EventIdType_

#define _DEFINED_TYPEDEF_FOR_Dem_EventStatusExtendedType_

#define _DEFINED_TYPEDEF_FOR_Dem_EventStatusType_

#define _DEFINED_TYPEDEF_FOR_Dem_IndicatorStatusType_

#define _DEFINED_TYPEDEF_FOR_Dem_InitMonitorReasonType_

#define _DEFINED_TYPEDEF_FOR_Dem_MaxDataValueType_

#define _DEFINED_TYPEDEF_FOR_Dem_OperationCycleIdType_

#define _DEFINED_TYPEDEF_FOR_Dem_OperationCycleStateType_

#define _DEFINED_TYPEDEF_FOR_Dem_ReturnClearDTCType_

#define _DEFINED_TYPEDEF_FOR_DigitalLevel_

#define _DEFINED_TYPEDEF_FOR_DutyCycle_

#define _DEFINED_TYPEDEF_FOR_EcuM_BootTargetType_

#define _DEFINED_TYPEDEF_FOR_EcuM_StateType_

#define _DEFINED_TYPEDEF_FOR_EcuM_UserType_

#define _DEFINED_TYPEDEF_FOR_Frequency_

#define _DEFINED_TYPEDEF_FOR_IoHwAb_SignalType__

#define _DEFINED_TYPEDEF_FOR_NvM_BlockIdType_

#define _DEFINED_TYPEDEF_FOR_NvM_RequestResultType_

#define _DEFINED_TYPEDEF_FOR_SignalQuality_

#define _DEFINED_TYPEDEF_FOR_VoidPtr_

#endif /* RTE_TYPE_WORKAROUNDS_H_ */
